version: "3.7"
services:
  app:
    build:
      args:
        user: ahmad
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8282:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

networks:
  default:
    external:
      name: php_default
